CREATE USER arenauser WITH PASSWORD 'arenauser';

DROP DATABASE arena;
CREATE DATABASE arena;
\c arena arenauser

CREATE TABLE if NOT EXISTS client(
    id INTEGER NOT NULL,
    username  VARCHAR(35) NOT NULL UNIQUE,
    displayname VARCHAR(35) NULL,
    pass VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    birthdate DATE NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)

);

INSERT INTO client (id, username,displayname,pass,email,birthdate) VALUES (12345, 'josias','brtt','lalala','blabla@','2020-12-01');
INSERT INTO client (id, username,displayname,pass,email,birthdate) VALUES (54321, 'mylon','mylon','lalala','blabla@1','2020-12-01');

CREATE TABLE if NOT EXISTS sport(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    sportname VARCHAR(255) NOT NULL 
);

INSERT INTO sport(sportname) VALUES ('LOL');